// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBxKVtE1yP7nCrX8PfDv8IyJv1KW1gkEE',
    appId: '1:51055881424:web:d4ed2d831e74daa86602d5',
    messagingSenderId: '51055881424',
    projectId: 'flutter-brl',
    authDomain: 'flutter-brl.firebaseapp.com',
    storageBucket: 'flutter-brl.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbzk3NVAYcR-EQHAoyl4bZ9NsQS29DOpo',
    appId: '1:51055881424:android:362d30ed7d92d9366602d5',
    messagingSenderId: '51055881424',
    projectId: 'flutter-brl',
    storageBucket: 'flutter-brl.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7EcPR0R0n3cKV2hTUpQzyktlJxCtMWkA',
    appId: '1:51055881424:ios:90693935a4feb9f26602d5',
    messagingSenderId: '51055881424',
    projectId: 'flutter-brl',
    storageBucket: 'flutter-brl.firebasestorage.app',
    iosBundleId: 'com.example.flutteranew',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA7EcPR0R0n3cKV2hTUpQzyktlJxCtMWkA',
    appId: '1:51055881424:ios:90693935a4feb9f26602d5',
    messagingSenderId: '51055881424',
    projectId: 'flutter-brl',
    storageBucket: 'flutter-brl.firebasestorage.app',
    iosBundleId: 'com.example.flutteranew',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBBxKVtE1yP7nCrX8PfDv8IyJv1KW1gkEE',
    appId: '1:51055881424:web:3fd5ca414b90c06c6602d5',
    messagingSenderId: '51055881424',
    projectId: 'flutter-brl',
    authDomain: 'flutter-brl.firebaseapp.com',
    storageBucket: 'flutter-brl.firebasestorage.app',
  );
}
